### ISSUE TITLE
Adapting course material - citation/attribution

### ISSUE THREAD

**Issue by dvalters** [SciTools/courses#145]
Hi there,

I just wanted to check if it is OK to use these course materials as the basis for an Iris tutorial I am writing for https://github.com/ourcodingclub/ourcodingclub.github.io (I have to develop the materials in a set layout/format, otherwise I would just deliver the course 'as is' from the notebook.)

I see it's GPL licensed but just wanted to check if you have any specific citation/attribution, or copyright messages you would like included. (Other than the GPL)

Best wishes,
Declan

University of Edinburgh GeoSciences

**Comment by kaedonkers** [comment]
Hi Declan! It is great to hear you would like to use the course! (Also apologies for the late response...)

AFAIK it is OK for you to adapt the course for your own uses, however I do not know of any specific citations/attribution/copyright messages required by the SciTools organisation. Given that most of the SciTools organisation is Crown Copyright I will have to defer this to @pelson, @bjlittle & @dkillick.

**Comment by dvalters** [comment]
@dkillick, @kaedonkers Thanks for clarifying - will do 😃
