### ISSUE TITLE
Broken Link to iris.save documentation

### ISSUE THREAD

**Issue by Daniel-Joe-Griffin** [SciTools/courses#182]
In the Iris course Chapter 2.2. Saving Cubes, there is a link to iris.save documentation that does not work: https://scitools.org.uk/iris/docs/latest/iris/iris.html#iris.save

It should be updated to this link: https://scitools-iris.readthedocs.io/en/stable/userguide/saving_iris_cubes.html?highlight=iris.save#saving-iris-cubes

**Comment by tkknight** [comment]
Thanks for raising this @Daniel-Joe-Griffin .  We moved the Iris documentation from **GitHub** **pages** (https://scitools.org.uk/iris/docs/v2.4.0/index.html) to **Read the Docs** (https://scitools-iris.readthedocs.io/en/latest/) for Iris 3 and we clearly need to update any references in this course material.
