### ISSUE TITLE
Out of date coordinate creation loop in: Iris Tutorial, Chapter 4

### ISSUE THREAD

**Issue by ESadek-MO** [SciTools/courses#185]
In code block 19, new coordinates are being added to a cube to allow for a merge. However, units are not hard coded, which causes them to load as `unknown`, whereas existing coordinates have units of `1`. Potential solution below, although suitable explanation will also be needed to be added. 

![image](https://user-images.githubusercontent.com/110238618/183054328-5ca3abf2-4f38-4328-ac6c-b3bca4598c69.png)

**Comment by rcomer** [comment]
For info, there is a related example in the gallery:
https://scitools-iris.readthedocs.io/en/latest/generated/gallery/meteorology/plot_lagged_ensemble.html
