### ISSUE TITLE
Feedback from NumPy course (02/16)

### ISSUE THREAD

**Issue by dkillick** [SciTools/courses#26]
The course needs more exercises - there are long sections of teaching with no breaks / changes of style.
- [ ] For example, a short exercise (on creating/indexing arrays?) before &sect;Multidimensional Array Creation.
- [x] Change the values / number of points in the `x` and `y` arrays in the final exercise.

**Comment by pelson** [comment]
:+1: - yes please!

**Comment by dkillick** [comment]
> Change the values / number of points in the x and y arrays in the final exercise.

Done in #29.
