### ISSUE TITLE
Sections to possibly remove from Iris course (04/16)

### ISSUE THREAD

**Issue by dkillick** [SciTools/courses#36]
Sections of the Iris course that may be excess to requirements and could be removed without leaving a big unfilled gap in what the Iris course teaches:
- [ ] **cell - cell comparisons:** the section on cell - point comparisons show that cell comparisons are possible. The section on cell - cell comparisons just goes back over this but makes the situation far more complex as it just isn't clear why cell - cell comparisons behave as they do.
- [ ] **Partial datetimes:** in many ways they don't add anything that you can't do with a cell datetime object.

**Comment by pelson** [comment]
> Partial datetimes: in many ways they don't add anything that you can't do with a cell datetime object.

Agreed. We aren't seeing the benefit from PartialDatetimes until the netcdftime object can be handled by them.

> The section on cell - cell comparisons just goes back over this but makes the situation far more complex as it just isn't clear why cell - cell comparisons behave as they do.

This is an important message though. Perhaps we should re-write, rather than delete.

**Comment by pelson** [comment]
In the interests of issue hygiene, I'm going to go ahead and close this issue. The courses are a movable feast, and changes that can be justified and bought-into by others are easy to accommodate.
