### ISSUE TITLE
Missing html files

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/courses#37]
The [make.sh](https://github.com/SciTools/courses/blob/master/make.sh) would suggest that html files should be made, but this doesn't seem to be the case.

**Comment by lbdreyer** [comment]
pandoc isn't installed internally, so unless this is a simple fix, we will have to use old copies of the courses (I have copies from 14th April) as handouts to teach next week.

**Comment by pelson** [comment]
Looks like `jupyter nbconvert --to html` defaults to putting the output in the same directory as the input, rather than the PWD. I'll put forward a PR shortly.

**Comment by pelson** [comment]
Closed by #38.
