### ISSUE TITLE
Feedback from Iris course on 08/16

### ISSUE THREAD

**Issue by bjlittle** [SciTools/courses#39]
Use working examples that may appeal/taylored to scientists from:
- applied science
- climate science
- foundation science
- weather science

**Comment by pelson** [comment]
Not sure I could take this forward as an action for 2 reasons:

 * I'd need more clarity on what "working examples" actually meant (does it mean real Scientist code?)

 * I'd be extremely reluctant to *extend* the scope of the iris course (though I totally want to do what you are describing in *a new* course)

Just my 2 cents 😉

**Comment by bjlittle** [comment]
@pelson I just wanted this captured (somewhere), rather than forgotten. Totally agree with your concerns.

The reference to `working examples` was related to, if possible, the choice of scenario used to highlight/explain the capabilities of specific functionality within Iris e.g. calculating decadal means using `aggregated_by` might be more relevant to a climate scientist rather than a weather scientist.

I guess my point is that we should tailor how we're selling Iris to a specific audience ... and that would be a *new* course ... or set of courses.

Yeah, and I guess shortly you will have 2 cents to spend, enjoy [scipy2016](http://scipy2016.scipy.org/ehome/index.php?eventid=146062&tabid=332930&) :wink:

**Comment by pelson** [comment]
There have been a number of iterations on the material since this feedback. Closing as some of this is probably now obsolete.
