### ISSUE TITLE
course feedback 1mar

### ISSUE THREAD

**Issue by marqh** [SciTools/courses#80]
https://github.com/SciTools/courses/blob/a5e4a5f88d4f8c8590dc3dd6fc2ca40199031270/course_content/notebooks/numpy_intro.ipynb

```
result of arr_2d[0, ::2] is [[1, 3], [4, 6]]
```
wrong!   `arr_2d[0:, ::2]`

```
the first column, retaining the outside dimension: resulting in [[1, 4]]
```
tricksy, intentional??

conditional indexing is useful and interesting, include?
```
print(np.where(arr_2d == 4))
print(arr_2d[arr_2d % 2 == 0])
```

The Array Object: Summary of key points
 * properties : shape, dtype
 * arrays are homogeneous, all elements have the same type: dtype
 * creation : array([list]), ones, zeros, arange, linspace
   *   **indexing arrays to produce further arrays, subsets of the original**
   *   **multi-dimensional indexing and conditional indexing**
 * ~~indexing like Python objects : integers and slices~~
 * ~~indexing produces further array objects~~
 * ~~multi-dimensional indexing with multiple indices~~
 * ~~indexing differences from list-of-lists~~

desired_result = np.array([[  1,   2,   3],
                           [104, 105, 406],
                           [407, 40~~7~~ **8**, 409]])

You can assume that the ordering of the values is the same as in the earlier example. That is, the order is [day1-station1, day1-station2, day1-station3, day2-station1, ...] and so on.
  
this is not clear enough, needs another look

lessons for calcs: 
 * defensive programming
 * clear syntax

masked array:
 * how to unmask a masked value
 * space for the exercise (new cell)

efficiency
 * when to optimise, as well as how
 *

**Comment by pelson** [comment]
There have been a number of iterations on the material since this feedback. Closing as some of this is probably now obsolete.
